services:
  kodus-proto:
    container_name: kodus-proto
    image: kodus/kodus-proto:latest
    build:
      context: .
      dockerfile: DockerFiles/DockerFile
    volumes:
      - .:/workspace
    command: ["generate"]
